services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8443:443"
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-DBpassword}@db:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=utf8
      MAILER_DSN: smtp://mailpit:1025
      MAILER_FROM: noreply@ecliptix.local
      VERIFY_EMAIL_URL: https://localhost:8443
    volumes:
      - ./:/app:rw
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost/docs >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php bin/console messenger:consume async --memory-limit=128M --time-limit=3600
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-DBpassword}@db:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=utf8
      MAILER_DSN: smtp://mailpit:1025
    volumes:
      - ./:/app:rw
    depends_on:
      db:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"

  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-DBpassword}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  caddy_data:
  caddy_config:
  database_data:
