<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630094846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE active_elixir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, item_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3CF83D8E1136BE75 ON active_elixir (character_id)');
        $this->addSql('CREATE INDEX IDX_3CF83D8E3DB201CA ON active_elixir (item_definition_id)');
        $this->addSql('ALTER TABLE active_elixir ADD CONSTRAINT FK_3CF83D8E1136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE active_elixir ADD CONSTRAINT FK_3CF83D8E3DB201CA FOREIGN KEY (item_definition_id) REFERENCES item_definition (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE active_elixir DROP CONSTRAINT FK_3CF83D8E1136BE75');
        $this->addSql('ALTER TABLE active_elixir DROP CONSTRAINT FK_3CF83D8E3DB201CA');
        $this->addSql('DROP TABLE active_elixir');
    }
}
