<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260510135136 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shop_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gold_price INT NOT NULL, diamond_price INT NOT NULL, slot VARCHAR(255) NOT NULL, rotation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EEC0DD6C326CE1FB ON shop_offer (rotation_id)');
        $this->addSql('ALTER TABLE shop_offer ADD CONSTRAINT FK_EEC0DD6C326CE1FB FOREIGN KEY (rotation_id) REFERENCES shop_rotation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shop_offer DROP CONSTRAINT FK_EEC0DD6C326CE1FB');
        $this->addSql('DROP TABLE shop_offer');
    }
}
