<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260729175158 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appearance_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, sort_order INT DEFAULT NULL, race_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AB4AF796E59D40D ON appearance_option (race_id)');
        $this->addSql('CREATE TABLE email_verification_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token UUID NOT NULL, exipres_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C4995C671136BE75 ON email_verification_token (character_id)');
        $this->addSql('CREATE TABLE race (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE appearance_option ADD CONSTRAINT FK_6AB4AF796E59D40D FOREIGN KEY (race_id) REFERENCES race (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE email_verification_token ADD CONSTRAINT FK_C4995C671136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appearance_option DROP CONSTRAINT FK_6AB4AF796E59D40D');
        $this->addSql('ALTER TABLE email_verification_token DROP CONSTRAINT FK_C4995C671136BE75');
        $this->addSql('DROP TABLE appearance_option');
        $this->addSql('DROP TABLE email_verification_token');
        $this->addSql('DROP TABLE race');
    }
}
