<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260508211145 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shop_rotation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, valid_from DATE NOT NULL, valid_until DATE NOT NULL, character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F2C462671136BE75 ON shop_rotation (character_id)');
        $this->addSql('ALTER TABLE shop_rotation ADD CONSTRAINT FK_F2C462671136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shop_rotation DROP CONSTRAINT FK_F2C462671136BE75');
        $this->addSql('DROP TABLE shop_rotation');
    }
}
