<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260730163714 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE password_reset_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, character_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B7BA4B61136BE75 ON password_reset_token (character_id)');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT FK_6B7BA4B61136BE75 FOREIGN KEY (character_id) REFERENCES character (id)');
        $this->addSql('ALTER TABLE "character" ADD email_verified BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE "character" ADD race_id INT NOT NULL');
        $this->addSql('ALTER TABLE "character" ADD hair_id INT NOT NULL');
        $this->addSql('ALTER TABLE "character" ADD eyes_id INT NOT NULL');
        $this->addSql('ALTER TABLE "character" ADD mouth_id INT NOT NULL');
        $this->addSql('ALTER TABLE "character" ADD nose_id INT NOT NULL');
        $this->addSql('ALTER TABLE "character" ADD ears_id INT NOT NULL');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB0346E59D40D FOREIGN KEY (race_id) REFERENCES race (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB0342A89600A FOREIGN KEY (hair_id) REFERENCES appearance_option (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB034D9970B58 FOREIGN KEY (eyes_id) REFERENCES appearance_option (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB034631D4FBC FOREIGN KEY (mouth_id) REFERENCES appearance_option (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB03494CDD445 FOREIGN KEY (nose_id) REFERENCES appearance_option (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB034E4D2C03C FOREIGN KEY (ears_id) REFERENCES appearance_option (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_937AB0346E59D40D ON "character" (race_id)');
        $this->addSql('CREATE INDEX IDX_937AB0342A89600A ON "character" (hair_id)');
        $this->addSql('CREATE INDEX IDX_937AB034D9970B58 ON "character" (eyes_id)');
        $this->addSql('CREATE INDEX IDX_937AB034631D4FBC ON "character" (mouth_id)');
        $this->addSql('CREATE INDEX IDX_937AB03494CDD445 ON "character" (nose_id)');
        $this->addSql('CREATE INDEX IDX_937AB034E4D2C03C ON "character" (ears_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE password_reset_token DROP CONSTRAINT FK_6B7BA4B61136BE75');
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB0346E59D40D');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB0342A89600A');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB034D9970B58');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB034631D4FBC');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB03494CDD445');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB034E4D2C03C');
        $this->addSql('DROP INDEX IDX_937AB0346E59D40D');
        $this->addSql('DROP INDEX IDX_937AB0342A89600A');
        $this->addSql('DROP INDEX IDX_937AB034D9970B58');
        $this->addSql('DROP INDEX IDX_937AB034631D4FBC');
        $this->addSql('DROP INDEX IDX_937AB03494CDD445');
        $this->addSql('DROP INDEX IDX_937AB034E4D2C03C');
        $this->addSql('ALTER TABLE character DROP email_verified');
        $this->addSql('ALTER TABLE character DROP race_id');
        $this->addSql('ALTER TABLE character DROP hair_id');
        $this->addSql('ALTER TABLE character DROP eyes_id');
        $this->addSql('ALTER TABLE character DROP mouth_id');
        $this->addSql('ALTER TABLE character DROP nose_id');
        $this->addSql('ALTER TABLE character DROP ears_id');
    }
}
