<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520121957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE item (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            bonus_damage INT NOT NULL,
            bonus_crit INT NOT NULL,
            bonus_health INT NOT NULL,
            definition_id INT NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_1F1B251ED11EA911 ON item (definition_id)');
        $this->addSql('CREATE TABLE item_definition (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            desired_slot VARCHAR(255) NOT NULL,
            base_damage INT NOT NULL,
            base_crit INT NOT NULL,
            base_health INT NOT NULL,
            required_level INT NOT NULL,
            description TEXT DEFAULT NULL,
            PRIMARY KEY (id))
        ');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251ED11EA911 FOREIGN KEY (definition_id) REFERENCES item_definition (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251ED11EA911');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_definition');
    }
}
