<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521172454 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_inventory (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            equipped BOOLEAN NOT NULL,
            quantity INT NOT NULL,
            character_id INT NOT NULL,
            item_id INT DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_367DE80D1136BE75 ON character_inventory (character_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_367DE80D126F525E ON character_inventory (item_id)');
        $this->addSql('ALTER TABLE character_inventory ADD CONSTRAINT FK_367DE80D1136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_inventory ADD CONSTRAINT FK_367DE80D126F525E FOREIGN KEY (item_id) REFERENCES item (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_inventory DROP CONSTRAINT FK_367DE80D1136BE75');
        $this->addSql('ALTER TABLE character_inventory DROP CONSTRAINT FK_367DE80D126F525E');
        $this->addSql('DROP TABLE character_inventory');
    }
}
