<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723194044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE friend_relation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, character_id INT NOT NULL, friend_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F56F2103AC24F853D956F010 ON friend_relation (character_id, friend_id)');
        $this->addSql('CREATE INDEX IDX_F56F2103AC24F853 ON friend_relation (character_id)');
        $this->addSql('CREATE INDEX IDX_F56F2103D956F010 ON friend_relation (friend_id)');
        $this->addSql('ALTER TABLE friend_relation ADD CONSTRAINT FK_F56F2103AC24F853 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friend_relation ADD CONSTRAINT FK_F56F2103D956F010 FOREIGN KEY (friend_id) REFERENCES character (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE friend_relation DROP CONSTRAINT FK_F56F2103AC24F853');
        $this->addSql('ALTER TABLE friend_relation DROP CONSTRAINT FK_F56F2103D956F010');
        $this->addSql('DROP TABLE friend_relation');
    }
}
